### ISSUE TITLE
TypeError: in method 'IndexIDMap_add_with_ids', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t const *'

### ISSUE THREAD

**Issue by nithinreddyy** [99sbr/semantic-search-with-sbert#1]
**When i'm trying to run the code in local jupyter notebook windows 10, it's throwing an error for below code**

```
encoded_data = model.encode(df.Plot.tolist())
encoded_data = np.asarray(encoded_data.astype('float32'))
index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
index.add_with_ids(encoded_data, np.array(range(0, len(df))))
faiss.write_index(index, 'movie_plot.index')
```

The error is :

```
TypeError                                 Traceback (most recent call last)
<ipython-input-26-22c477f27f62> in <module>
----> 1 index.add_with_ids(encoded_data, np.array(range(0, len(df))))
      2 faiss.write_index(index, 'movie_plot.index')

~\t5\lib\site-packages\faiss\__init__.py in replacement_add_with_ids(self, x, ids)
    233 
    234         assert ids.shape == (n, ), 'not same nb of vectors as ids'
--> 235         self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
    236 
    237     def replacement_assign(self, x, k, labels=None):

~\t5\lib\site-packages\faiss\swigfaiss.py in add_with_ids(self, n, x, xids)
   4950 
   4951     def add_with_ids(self, n, x, xids):
-> 4952         return _swigfaiss.IndexIDMap_add_with_ids(self, n, x, xids)
   4953 
   4954     def add(self, n, x):

TypeError: in method 'IndexIDMap_add_with_ids', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t const *'
```

**I installed all required libraries and for faiss i installed pip install faiss-cpu**

**Comment by 99sbr** [comment]
Did you install pip install faiss-cpu or faiss-gpu ?

**Comment by 99sbr** [comment]
Check your encoded_data shape is 768 or not? i hope you are using the same model. a screenshot will help. Also try without float32 thing

**Comment by nithinreddyy** [comment]
We have convert ids into int64.

```
encoded_data = model.encode(df.Plot.tolist())
encoded_data = np.asarray(encoded_data.astype('float32'))
index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
ids = np.array(range(0, len(df)))
ids = np.asarray(ids.astype('int64'))
index.add_with_ids(encoded_data, ids)
faiss.write_index(index, 'movie_plot.index')
```

**Comment by nithinreddyy** [comment]
How to disable cuda? I don't have any graphic card for my lappy. Can we run the code without cuda?

```
with open('generated_queries_all.tsv', 'w') as fOut:
    for start_idx in tqdm(range(0, len(paragraphs), batch_size)):
        sub_paragraphs = paragraphs[start_idx:start_idx+batch_size]
        inputs = tokenizer.prepare_seq2seq_batch(sub_paragraphs, max_length=max_length_paragraph, truncation=True, return_tensors='pt').to(device)
        outputs = model.generate(
            **inputs,
            max_length=max_length_query,
            do_sample=True,
            top_p=0.95,
            num_return_sequences=num_queries)

        for idx, out in enumerate(outputs):
            query = tokenizer.decode(out, skip_special_tokens=True)
            query = _removeNonAscii(query)
            para = sub_paragraphs[int(idx/num_queries)]
            para = _removeNonAscii(para)
            fOut.write("{}\t{}\n".format(query.replace("\t", " ").strip(), para.replace("\t", " ").strip()))
```

The error it's throwing is :

`NameError: name 'device' is not defined`

**Comment by 99sbr** [comment]
> `NameError: name 'device' is not defined`

If you are running my code without change on cell 16 i have defined 

#Select the device
device = 'cuda'
model.to(device)

if you are not using gpu you can specify device as 'cpu'

**Comment by 99sbr** [comment]
> We have convert ids into int64.
> 
> ```
> encoded_data = model.encode(df.Plot.tolist())
> encoded_data = np.asarray(encoded_data.astype('float32'))
> index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
> ids = np.array(range(0, len(df)))
> ids = np.asarray(ids.astype('int64'))
> index.add_with_ids(encoded_data, ids)
> faiss.write_index(index, 'movie_plot.index')
> ```

You dont have to convert index to int . it is already taken care

**Comment by nithinreddyy** [comment]
> > We have convert ids into int64.
> > ```
> > encoded_data = model.encode(df.Plot.tolist())
> > encoded_data = np.asarray(encoded_data.astype('float32'))
> > index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
> > ids = np.array(range(0, len(df)))
> > ids = np.asarray(ids.astype('int64'))
> > index.add_with_ids(encoded_data, ids)
> > faiss.write_index(index, 'movie_plot.index')
> > ```
> 
> You don't have to convert the index to int. it is already taken care

But if you're running your code in jupyter notebook windows 10, we have to do this. Changing ids to int64. And we have to install ipywidgets and jupyter

pip install ipywidgets
pip install jupyter

**Comment by 99sbr** [comment]
" And we have to install ipywidgets and jupyter" how is this related to the error you are getting?

Also i ran your code on my local (macos) and it is not giving me any error. I am still not sure what is your error. could you share some error screen shot with the code  you are running?

Also please share below details
(1) model used and the encoded vector shape
(2) windows 32 or 64
(3) see if you are getting error without int64 or float32 thing

**Comment by nithinreddyy** [comment]
> " And we have to install ipywidgets and jupyter" how is this related to the error you are getting?
> 
> Also i ran your code on my local (macos) and it is not giving me any error. I am still not sure what is your error. could you share some error screen shot with the code you are running?
> 
> Also please share below details
> (1) model used and the encoded vector shape
> (2) windows 32 or 64
> (3) see if you are getting error without int64 or float32 thing

If you're running the code in jupyter notebook, first we have to change the ids into int64, before fitting the model we have to install ipywidgets and jupyter. When I tried to fit the model, it returned an error like ipywidgets and jupyter is not installed

**Comment by nithinreddyy** [comment]
`encoded_data = model.encode(df.Plot.tolist())`

Can we save the encoded_data into pickle and load the file directly? Does that work? Because it's taking almost 10 mins to encode the data with 2000 rows

And what's the use of movie_plot.index?

`faiss.write_index(index, 'movie_plot.index')`

**Comment by 99sbr** [comment]
faiss.write_index(index, 'movie_plot.index') this does exactly what you asked. saving the embeddings in index file
