### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1) for index.add_with_ids(encoded_data, ids)

### ISSUE THREAD

**Issue by nithinreddyy** [99sbr/semantic-search-with-sbert#2]
**ValueError: not enough values to unpack (expected 2, got 1) for index.add_with_ids(encoded_data, ids)**

I'm trying to encode the data with the help of below data and code

`print(df)`

Output is : 

```
 Pdf                Content                                            Page no
July 20, 2016.PDF   RESERVE BANK OF INDIA DEPARTMENT OF CURRENCY M...  3.0
July 20, 2016.PDF   RESERVE BANK OF INDIA DEPARTMENT OF CURRENCY M...  3.0 
July 20, 2016.PDF   Para 1 Authority to Impound Counterfeit Notes ...  3.0  
July 20, 2016.PDF   (i) All branches of Public Sector Banks.           3.0
July 20, 2016.PDF   (ii) All branches of Private Sector Banks and ...  3.0
...                            ...                                                                                                 
April 1, 2021.pdf   4. Motif of Mangalayan depicting the country’s...  21.0              
April 1, 2021.pdf   5. Denominational numeral २००० in Devnagari        21.0                       
April 1, 2021.pdf   side. For visually impaired Intaglio or raised...  21.0                      
April 1, 2021.pdf   11. Horizontal rectangle with ₹2000 in raised ...  21.0                       
April 1, 2021.pdf   12. Seven angular bleed lines on left and righ...  21.0                       
```

And the code is below : 

```
encoded_data = model.encode(str(df.Content.tolist()))
encoded_data = np.asarray(encoded_data.astype('float32'))
index = faiss.IndexIDMap(faiss.IndexFlatIP(768))
ids = np.array(range(0, len(df)))
ids = np.asarray(ids.astype('int64'))
index.add_with_ids(encoded_data, ids)
```

The error is with the line of code **index.add_with_ids(encoded_data, ids)**

The error it's returning is :

```
ValueError                                Traceback (most recent call last)
<ipython-input-32-791ec30482ee> in <module>
----> 1 index.add_with_ids(encoded_data, ids)

~\t5\lib\site-packages\faiss\__init__.py in replacement_add_with_ids(self, x, ids)
    229             in result lists to mean "not found" so it's better to not use it as an id.
    230         """
--> 231         n, d = x.shape
    232         assert d == self.d
    233 

ValueError: not enough values to unpack (expected 2, got 1)
```

**When i'm trying to add index.add_with_ids(encoded_data, ids), it's returning error like ValueError: not enough values to unpack (expected 2, got 1)**

**Comment by 99sbr** [comment]
**
![Screenshot 2021-06-28 at 12 50 00](https://user-images.githubusercontent.com/17409469/123596110-5b220f80-d80f-11eb-91ad-3720de548b08.png)
`model.encode(str(df.Content.tolist()))`
 
 This is incorrect. You have converted all your data into a single string. What you need to do is 
 `data = [str(elm) for elm in data]`

**Comment by nithinreddyy** [comment]
> **
> ![Screenshot 2021-06-28 at 12 50 00](https://user-images.githubusercontent.com/17409469/123596110-5b220f80-d80f-11eb-91ad-3720de548b08.png)
> `model.encode(str(df.Content.tolist()))`
> 
> This is incorrect. You have converted all your data into a single string. What you need to do is
> `data = [str(elm) for elm in data]`

This is working fine.
